In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import linear_model

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
df = df.fillna(5)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       5.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [9]:
reg.coef_

array([  128.43512778,  5913.51964731, -4902.54602054])

In [10]:
reg.intercept_

264780.0709546711

# Exercise

In [41]:
d = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv")

In [42]:
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [43]:
d=d.rename(columns = {"test_score(out of 10)":"testscore","interview_score(out of 10)":"intscore","salary($)":"salary"})
d

experience  testscore  intscore  salary
0        NaN        8.0         9   50000
1        NaN        8.0         6   45000
2       five        6.0         7   60000
3        two       10.0        10   65000
4      seven        9.0         6   70000
5      three        7.0        10   62000
6        ten        NaN         7   72000
7     eleven        7.0         8   80000

In [46]:
d.testscore = d.testscore.fillna(7,)

In [47]:
d

experience  testscore  intscore  salary
0        NaN        8.0         9   50000
1        NaN        8.0         6   45000
2       five        6.0         7   60000
3        two       10.0        10   65000
4      seven        9.0         6   70000
5      three        7.0        10   62000
6        ten        7.0         7   72000
7     eleven        7.0         8   80000

In [48]:
d.at[0,"experience"] = "two"

In [49]:
d

experience  testscore  intscore  salary
0        two        8.0         9   50000
1        NaN        8.0         6   45000
2       five        6.0         7   60000
3        two       10.0        10   65000
4      seven        9.0         6   70000
5      three        7.0        10   62000
6        ten        7.0         7   72000
7     eleven        7.0         8   80000

In [50]:
d.at[1,"experience"]="three"

In [51]:
d

experience  testscore  intscore  salary
0        two        8.0         9   50000
1      three        8.0         6   45000
2       five        6.0         7   60000
3        two       10.0        10   65000
4      seven        9.0         6   70000
5      three        7.0        10   62000
6        ten        7.0         7   72000
7     eleven        7.0         8   80000

In [52]:
from word2number import w2n

In [54]:
d.experience = d.experience.apply(w2n.word_to_num)
d

experience  testscore  intscore  salary
0           2        8.0         9   50000
1           3        8.0         6   45000
2           5        6.0         7   60000
3           2       10.0        10   65000
4           7        9.0         6   70000
5           3        7.0        10   62000
6          10        7.0         7   72000
7          11        7.0         8   80000

In [56]:
reg = linear_model.LinearRegression()
reg.fit(d[['experience','testscore','intscore']],d.salary)

LinearRegression()

In [57]:
reg.predict([[2,9,6]])

C:\Users\Atharva Paranjape\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([47918.78191235])

In [58]:
reg.predict([[12,10,10]])

C:\Users\Atharva Paranjape\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([98356.1143151])