In [5]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [35]:
b=np.array([[1,2],[3,4],[5,6]], dtype=complex)
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [8]:
print(b.ndim)

2


In [9]:
print(a.itemsize)

4


In [10]:
c=np.array([2.3,4.6,7.8])

In [11]:
print(c.itemsize)

8


In [13]:
print(a.dtype)
print(c.dtype)

int32
float64


In [14]:
print(b.size)
print(b)

6
[[1 2]
 [3 4]
 [5 6]]


In [15]:
print(b.shape)

(3, 2)


In [24]:
b=np.array([[1,2],[3,4],[5,6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
d=np.zeros((3,4))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
e=np.arange(1,5)
e

array([1, 2, 3, 4])

In [22]:
f=np.linspace(1,5,10)
f

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [33]:
g=b.reshape(2,3)
print(g)

[[1 2 3]
 [4 5 6]]


In [37]:
i=b.ravel()
i

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [39]:
b.min()

(1+0j)

In [42]:
b.sum()

(21+0j)

In [43]:
b.sum(axis=0)

array([ 9.+0.j, 12.+0.j])

In [44]:
b.sum(axis=1)

array([ 3.+0.j,  7.+0.j, 11.+0.j])

In [45]:
np.sqrt(b)

array([[1.        +0.j, 1.41421356+0.j],
       [1.73205081+0.j, 2.        +0.j],
       [2.23606798+0.j, 2.44948974+0.j]])

In [46]:
np.std(b)

1.707825127659933

In [47]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [48]:
x+y

array([[ 6,  8],
       [10, 12]])

In [49]:
x-y

array([[-4, -4],
       [-4, -4]])

In [50]:
x*y

array([[ 5, 12],
       [21, 32]])

In [51]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [52]:
x.dot(y)

array([[19, 22],
       [43, 50]])