In [1]:
import numpy as np

In [8]:
a=np.array([6,7,8])
print(a[-1])
print(a[0:2])

8
[6 7]


In [16]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[0:2,2])
print(b[-1,0:2])
print(b[:,1:2])

[3 6]
[7 8]
[[2]
 [5]
 [8]]


In [17]:
for n in b.flat:
    print(n)

1
2
3
4
5
6
7
8
9


In [21]:
x=np.arange(6).reshape(3,2)
y=np.arange(6,12).reshape(3,2)

In [22]:
print(x)
print(y)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [24]:
np.vstack((x,y))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
np.hstack((x,y))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [26]:
i=np.arange(12).reshape(3,4)
i

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
j=i>4
j

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [30]:
i[j]

array([ 5,  6,  7,  8,  9, 10, 11])

In [31]:
i[j]=0
i

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])